# 공통 데이터베이스 설정
spring:
  config:
    import: optional:file:../.env.local[.properties]
  batch:
    job:
      name: dummyDataJob
      enabled: true
    jdbc:
      initialize-schema: always
  
  profiles:
    active: local  # 기본값 로컬

  # Flyway 설정
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

# Jasypt 암호화 (설정 정보)
# 추후에 보강
jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}
    algorithm: PBEWithHMACSHA512AndAES_256
    key-obtention-iterations: 1000
    pool-size: 1

# 로깅
logging:
  level:
    root: INFO
    com.ureca.billing: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# AES 암호화(개인 정보 보호)
crypto:
  aes:
    key: ${AES_SECRET_KEY}
  hash:
    key: ${HASH_SECRET_KEY:Q8v9K2MZP0D3wF4xR5cN7yA1bT+JH=}